# Generated by Django 3.1.2 on 2020-11-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0002_auto_20201101_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('state', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
    ]
