# Generated by Django 3.1.2 on 2020-11-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCases',
            fields=[
                ('state', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('cases', models.PositiveIntegerField()),
                ('deaths', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'covid_cases',
                'managed': False,
            },
        ),
    ]
