# Generated by Django 3.1.5 on 2021-02-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0006_auto_20210207_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'managed': False},
        ),
    ]
